// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using trilha_net_fundamentos_desafio.Context;

#nullable disable

namespace trilha_net_fundamentos_desafio.Migrations
{
    [DbContext(typeof(VeiculoContext))]
    [Migration("20260113181208_AddPricesTable")]
    partial class AddPricesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Parking.Shared.Models.Prices", b =>
                {
                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<decimal>("Hourlyprice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Type");

                    b.ToTable("Prices");

                    b.HasData(
                        new
                        {
                            Type = 0,
                            Hourlyprice = 10.00m
                        },
                        new
                        {
                            Type = 1,
                            Hourlyprice = 5.00m
                        });
                });

            modelBuilder.Entity("Parking.Shared.Models.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("EffectiveHourlyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TicketPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Type");

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("Parking.Shared.Models.Veiculo", b =>
                {
                    b.HasOne("Parking.Shared.Models.Prices", "PricingPolicy")
                        .WithMany()
                        .HasForeignKey("Type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PricingPolicy");
                });
#pragma warning restore 612, 618
        }
    }
}
